include /etc/nginx/fastcgi_params;
fastcgi_param SCRIPT_FILENAME /opt/clog/server/standalone/public/index.php;
fastcgi_param SCRIPT_NAME /index.php;
fastcgi_param HTTPS on;
fastcgi_param HTTP_PROXY "";
fastcgi_pass unix:/run/clog/php.sock;
fastcgi_read_timeout 35s;
