# Mushr DNS — wildcard resolution for LAN services
listen-address=192.168.86.28
bind-interfaces
no-resolv
server=1.1.1.1
server=1.0.0.1
address=/space-needle/192.168.86.28
address=/loft.hsimah.com/192.168.86.28
address=/calavera/192.168.86.35
address=/fjord/192.168.86.30
address=/viking/192.168.86.26
